language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: N8HWpCBIoSGEal7TFHrat6PoKopzXFmgNU0wUjYOSFWfZaK/r3ph1tJg7r2pmsKsQYAdeFwdDMf5Gw1FjHRoyA/7WUbQoZS+VVskQvEcSb53Pcwf796KC0bqv4yhP6tjO8sacO53lYFAuV4IlS7nAEV9q4NHQG25mOsHYSMxQZ82HAOqLAjQ+/8lM/Wd4kko4UU5+fgVYm9BEPbmZqmg2n0dUbzUUXPyhIlTp/vYXYmlJFeObZVTEo7n3kyzZ4S9d7XYXHeOWst6aMCQJAdYSWkL8kckIomEDoIeRQxWPfQ/5ffuiyf4+C+Rfi1VNm439/gfzdRHE3+jJ/yM7EYXJm5k0Cw95T9ldHfnoUobL86eMFzzTzBfy07wQbEcjDlqvnymPL8xvonS340jivlL8REuD2C8bxMAYWz+qvJLxEDfQF2UV7kQZDwsoL98pRSPcguoa+6CZiffoQiNkZu5L5mjUA8ifYcAM0N9tDsegniZiFnPhztjG/szfSms9tLm/c1G+y4F4v8/eBpq4powJmIljjy+ZUvWyan/WJE0F+K1RFntxPAJ8uG4Uvjr+j+YS7SQZmJsLUpVKp2+i25+T1drBlt11Gd8HA1Q5jUiIz7z8uA+MgVtbffCK3OEmHQJ5Tyg2XSV5FCYndI1qAKF7D9ciOG1YPzrTA6nFA/WYko=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
